/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1b1d0eb94c8fab18c6944113cb6128cf)
interface __BaseEnv_Env {
	FUNNEL_ANALYTICS: AnalyticsEngineDataset;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	NEXT_PUBLIC_APP_URL: "https://dispatchready.org";
	SUPPORT_EMAIL: "support@dispatchready.org";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_APP_URL" | "SUPPORT_EMAIL">> {}
}
